<?php


namespace App\Modules\Backend\KYC;

use App\Models\Certificate\KYCData;
use App\Modules\Framework\RepositoryImplementation;

class EloquentKYCRepository extends RepositoryImplementation implements KYCRepository
{

    public function getModel()
    {
        return new KYCData(); // TODO: Change the autogenerated stub
    }
}
