<?php


namespace App\Modules\Backend\BackDate;

use App\Models\Certificate\BackDate;
use App\Modules\Backend\BackDate\BackDataRepository;
use App\Modules\Framework\RepositoryImplementation;

class EloquentBackDataRepository extends RepositoryImplementation implements BackDataRepository
{

    public function getModel()
    {
        return new BackDate(); // TODO: Change the autogenerated stub
    }
}
