<?php


namespace App\Modules\Backend\Certificate\Repositories;


use App\Models\Certificate\Certificate;
use App\Modules\Framework\RepositoryImplementation;

class EloquentCertificateRepository extends RepositoryImplementation implements CertificateRepository
{

    public function getModel()
    {
        return new Certificate(); // TODO: Change the autogenerated stub
    }

}
