<?php


namespace App\Modules\Backend\CertificateHistory\Repositories;


use App\Models\Certificate\CertificateHistory;
use App\Modules\Backend\CertificateHistory\Repositories\CertificateHistoryRepository;
use App\Modules\Framework\RepositoryImplementation;

class EloquentCertificateHistoryRepository extends RepositoryImplementation implements CertificateHistoryRepository
{

    public function getModel()
    {
        return new CertificateHistory(); // TODO: Change the autogenerated stub
    }
}
