<?php


namespace App\Modules\Backend\CertificateHistoryDataBack\Repositories;

use App\Models\Certificate\CertificateHistoryData;
use App\Modules\Framework\RepositoryImplementation;

class EloquentCertificateHistoryDataBackRepository extends RepositoryImplementation implements CertificateHistoryDataBackRepository
{

    public function getModel()
    {
        return new CertificateHistoryData(); // TODO: Change the autogenerated stub
    }
}
